<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_form_alter().
 */
function palindrome_checker_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if ($form_id === 'palindrome_checker_form' && isset($form['name'])) {
        $form["#title"] = t("Palindrome checker");
        $form["name"]["#title"] = t("Check if a word is a palindrome:");
        $form["name"]["#attributes"]["placeholder"] = t("Enter a word");
    }
}

/**
 * Implements hook_preprocess_page().
 */
function palindrome_checker_preprocess_page(&$variables) {
    // set a variable for use in the page template.
    $variables["palindrome_checker_variable"] = t("Module to check if a word is a palindrome.");
}

/**
 * Implements hook_help().
 */
function palindrome_checker_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case "help.page.palindrome_checker":
            return [
                '#markup' => '<p>' . t("Check if a word is a palindrome.") . '</p>',
            ];
        default:
            // return an empty array if the route is not matched.
            return [];
    }
}
